### ISSUE TITLE
VR mod for other devices besides Quest?

### ISSUE THREAD

**Issue by EitanBlumin** [DrBeef/JKXR_public#1]
I have the full JK2 game, and I got a valve index VR set.
Are there plans for releasing a VR mod that could work on index and other VR devices besides Quest?
Where do I sign up for a waitlist? Where do I sign a petition to make this made? I couldn't find anything :(

Your mod looks amazing!
But please don't force me to buy a new VR set just for this, even though I already have one.
Thank you.

**Comment by DrBeef** [comment]
This can also be played on the Pico 4 (and Pico 3 Neo). PCVR support is planned for sometime in the future when but no timescale as to when that will be.
