### ISSUE TITLE
Oculus Quest 3 FOV

### ISSUE THREAD

**Issue by MarrowB83** [DrBeef/JKXR_public#3]
Hello,

having this great port on Oculus Quest 3 is working like a charm! Do you think it would be possible to create some addon, to make a FOV from older Quest 2 (95 degrees), to a new Quest 3 (110 degrees)?

Thank you very much! :-)

**Comment by baggyg** [comment]
I presume you are talking about some of the objects that disappear right on the edges. This is fixed on the Patreon version and will be rolled out when released pretty soon.

**Comment by MarrowB83** [comment]
You are great, thank you!
